### ISSUE TITLE
Sichtbarkeit im Plot

### ISSUE THREAD

**Issue by Astroschlumpf** [TP1-HHU/hw7#1]
Hallo zusammen!

Reicht es nur die Kurven für das leichte Objekt, die durch die gegebenen DGLs festgelegt werden, in den finalen Plots anzugeben oder sollen wir für das "Doppelsternsystem", das um (0,0) herum kreist, die Kurven ebenfalls einzuzeichnen?

Grüße
Oliver

**Comment by friedrichschluck** [comment]
Hallo Oliver,

meinst Du ein Kreis um die 0 würde das Bild besonders aufpeppen? Soll mir egal sein, interessant ist aber natürlich nur die Trajektorie des leichten Körpers.

**Comment by Astroschlumpf** [comment]
Danke für die Info. Ich hatte auch eher etwas komplizierteres mit zwei in einander verworrenen Ellipsen befürchtet. Ich kann aber auch noch nicht die Größenordnungen der Abstände einschätzen, vom Rest lasse ich mich überaschen.

**Comment by friedrichschluck** [comment]
Kleiner Tip am Rande: habe es eben selbst mal programmiert und festgestellt, dass man auch beim anfänglichen dt sehr aufpassen muss. Bei 1e-2 gings bei mir nicht, 1e-3 war dann richtig. Entweder ich hab noch einen anderen Fehler oder das ist so. Falls letzteres zutrifft werden wir das noch in der Aufgabenstellung ergänzen.

Viel Erfolg :) ich schließe mal hier, ok?
