### ISSUE TITLE
Unfertiger Code

### ISSUE THREAD

**Issue by Gandhi-uses-nukes** [TP1-HHU/hw7#4]
Nabend,

kann man seinen Code auch hochladen, wenn dieser noch "nicht ganz" funktioniert?

Ich habe zwei spezifische Fragen:

Mein dt wird bei jedem Durchlauf um ca. eine Größenordnung kleiner. hat einer vielleicht eine idee, was ich falsch gemacht haben könnte?
```c
double new_step(double Y4[], double Y5[], double dt){
	// Security Factor q:=0.5
	double q = 0.5;
	// Order of the RK method
	int p = 4;
	// Calculate H (local error)
	double H = max(
        abs(Y4[0]-Y5[0]),
        abs(Y4[1]-Y5[1]));
    H = max(
        H,
        abs(Y4[2]-Y5[2]));
    H = max(
        H,
        abs(Y4[3]-Y5[3]));

	// Calculate new dt
	dt = dt*q*pow( (TOL/H) , (1.0/(p+1)) );
```

Desweiteren habe ich die Funktion mal durch ein konstantes dt=10e-5 ersetzt, was jedoch nur dazu führte, dass die Werte geradlinig in die Unendlichkeit liefen. Offenbar steckt noch in der RK Implementation der Fehlerteufel ;)

Ist es denn überhaupt möglich, die Arrays für die RK4 und RK5 wie folgt zu definieren:
```C
	// For RK4 -> Y4 = [ x, y, x', y']
	double* Y4 = new double [4];

	// For RK5 -> Y5 = [ x, y, x', y']
	double* Y5 = new double [4];
	// Initial values at T=0
	Y4[0] = 0.994;
    Y4[1] = 0;
	Y4[2] = 0;
    Y4[3] = -2.00158510637908;

	Y5[0] = 0.994;
	Y5[1] = 0;
    Y5[2] = 0;
	Y5[3] = -2.00158510637908;
```

Wenn nichts dagegen spricht, mach ich mal ein Pull request, damit Ihr den ganzen Code einsehen könnt.

**Comment by goetzlehmann** [comment]
Ich habe mir den Code in Deinem Repository angeschaut. Soweit ich das einschätzen kann könnte das ganze an folgendem Missverständnis liegen.
Mit den Eingebetteten Methoden nimmt man *einen* Anfangswert (also *y_n*) und berechnet zwei *zwei* neue Lösungen, die 4. und die 5. Ordnungsapproximation zu *y_{n+1}*. Anschließend vergleicht man die beiden, zieht aus der Differenz den richtigen Schluss für die Schrittweite und nimmt für den nächsten Schritt die neue Schrittweite und den neu berechneten Wert aus RK4. Der neue Wert aus RK5 wird verworfen.
Wenn ich Deinen Code richtig verstehe, dann rechnest Du eigentlich Lösungen mit RK4 und RK5 getrennt voneinander weiter, benutzt aber die Differenz um etwas über die Schrittweite zu sagen. Ich vermute hier kommt es zu dem Unfug den Du beobachtest. 

Man kann das ganze noch ne Nummer besser bauen ist mir beim rumprobieren Aufgefallen: Angenommen der Algorithmus sagt uns, dass dt zu groß war und es kleiner sein sollte. Dann kann man natürlich auch den letzten Schritt noch mal wiederholen mit dem neu berechneten kleineren dt. So verwirft man manche Schritte, aber insgesamt macht es die Lösung genauer.

Grüße vom Flughafen in Paris :airplane:

**Comment by Gandhi-uses-nukes** [comment]
Nabend,

Es ist vollbracht, siehe bei den "Pull requests"
https://github.com/TP1-HHU/hw7/pull/6

![image](http://weknowmemes.com/wp-content/uploads/2014/05/reasons-to-like-france-graph.jpg)
:wink:

Schönes Rest Wochenende noch :sunglasses:
