### ISSUE TITLE
Energie des Systems

### ISSUE THREAD

**Issue by Astroschlumpf** [TP1-HHU/hw7#46]
Hallo zusammen!

Da ich derzeit einiges zu Stabilität und symplektischen Verfahren bei den ODE-Lösungsverfahren raussuche, habe ich mir die letzte Hausaufgabe noch einmal angeschaut. Um nicht noch einmal alles "zu Fuß" neu einzusetzen, wenn ich an den Anfangsbedinungen herumpfuschen will (es ging mir auch um die z-Komponente), habe ich das System in Matlab implementiert.

Mit dem üblichen ode45() erhalte ich zwar die erwartete Kurve, aber ebenso den Fehler, der bei nicht-symplektischen Verfahren auftreten sollte (Ende eines Umlaufes trifft nicht auf Anfang). Dabei ändert die Toleranz auch nichts, was demnach der Nachweis der Systematik ist. (Implementierung und Abbildung siehe https://github.com/Astroschlumpf/Nicht-Symplektische-Verfahren )

Gibt es mit den üblichen Paketen in Matlab einen einfachen Kniff das Verfahren so weit zu korrigieren, dass die Stabilitätsbedingungen erfüllt werden? Ich habe schon nach Implementierungen der angesprochenen symplektischen Lösungsverfahren gesucht, aber es schien mir, dass ich dadurch meine Installation stark beeinflusse (Pakete installieren etc.).

**Comment by goetzlehmann** [comment]
Hi Oliver, 
ersetz in Deinem Matlab Skript mal das Massenverhältnis genau durch das in der Aufgabe angesetzte, dann bekommst Du eine wesentlich bessere Übereinstimmung.
Zum Thema symplektische Integration: Also für einen Umlauf sollte das hier alles gut genug sein. Wie gut es ist findet man eigentlich im ersten Schritt raus, indem man mal die Energieerhaltung prüft. Dazu muss man mal die Formel für die Energie des Systems rausgraben. Ich denke für einen Umlauf sollte das alles gut genug sein.
Allgemein wirst Du vermutlich nicht drum herum kommen entweder selber einen symplektischen Integrator zu implementieren wenn Du wirklich einen brauchst. Ich denke keines der mit Matlab mitkommenden Verfahren ist symplektisch. Als erstes könnte man da einfach mal den symplektischen Euler probieren. Der geht am schnellsten zu implementieren.
Grüße!

**Comment by Astroschlumpf** [comment]
Ok, danke!
